{
    'name': "BackOffice Payroll",
    'version': '1.0',
    'depends': ['base','mail', 'board', 'approvals'], #,'account'
    'author': "Trusta Technology",
    'category': 'Services/Backoffice',
    'license': 'AGPL-3',
    'website': "www.trusta.co.id",
    'summary': "Lorem ipsum summary",
    'desciption': "Lorem ipsum description",
    'application': True,
    'installable': True,
    'data': [
        'security/bo_security.xml',
        'security/ir.model.access.csv',
        'views/backoffice.xml',
        'views/dropdown.xml',
        'views/website.xml',
        'views/resGroupExt.xml',
        'views/bankgroup.xml',
        'views/journalItemsExt.xml',
        'views/generalLedgerExt.xml',
        'views/bosettings.xml',
        'views/bankAccountExt.xml',
        'views/bankExt.xml',
        'views/stafftype.xml',
        'views/usersExt.xml',
        'views/bonus.xml',
        'views/bonustype.xml',
        'views/kategori.xml',
        'views/mistaketype.xml',
        'views/reports/backofficereports.xml',
        'views/approvalreq.xml',
        'views/dailyreports.xml',
        'views/reports/backofficereportsdaily.xml',
        'views/approvalcategory.xml',
        'views/rekapmasaaktif.xml',
        'views/reports/backofficeexcel.xml',
        'views/dashboard.xml',
        'views/dashboardvivi.xml',
        'views/approvalexecute.xml',
        'views/bonuswizard.xml',
        'views/backofficewizard.xml',
        'views/bankledgerentries.xml',
        'views/bankledgerentrieswizard.xml',
        'views/backoffice_setup.xml',
        'views/tampungform.xml',
        'views/backoffice_delete_setup.xml',
        'views/backoffice_menu.xml',
    ]
}